name: test multi-trigger
on:
  repository_dispatch:
    types: [dispatch-event]  
  workflow_dispatch:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        description: 'A token passed from the caller workflow'
        required: false
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test ||
      run: |
        echo ${{ github.event.client_payload.monday }}
      shell: bash  
    - uses: actions/checkout@v4   
      with:
        repository: lnxiang/monday
        ref: ${{ github.event.client_payload.monday }}
        path: monday
      #env:
      #  branch_name: ${{ !contains(github.event.client_payload.monday, main) }}

    - name: Build project
      run: |
        cd ${{ github.workspace }}/monday
        ./build.sh
      shell: bash
      
    - uses: actions/checkout@v4   
      with:
        repository: lnxiang/Tuesday
        ref: ${{ github.event.client_payload.Tuesday }}
        path: Tuesday
      #env:
      #  branch_name: ${{ github.event.client_payload.Tuesday }}

    - name: Build project
      run: |
        cd ${{ github.workspace }}/Tuesday
        ./build.sh 
      shell: bash
